name: QuantumEncoding

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Running Grover-Rudolph Algorithm
        run: | 
          python -m GroverRudolph
      - name: Testing
        run: | 
          cd test
          python -m TestGR