name: QuantumEncoding

on: [push]

jobs:
  GroverRudolph:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Running Grover-Rudolph Algorithm
        working-directory: ./GroverRudolph_LPW
        run: | 
          python -m GroverRudolph
      - name: Running Linear-Piecewise Function
        working-directory: ./GroverRudolph_LPW
        run: | 
          python -m Linear_Piecewise
      - name: Testing
        working-directory: ./GroverRudolph_LPW
        run: |
          python -m TestGR
  FixedRotations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Running Fixed Rotation For Inspiral
        working-directory: ./Fixed_Roations_GSP
        run: | 
          python -m inspiral_cal_k
      - name: Running Fixed Rotation For Whole Waveform
        working-directory: ./Fixed_Roations_GSP
        run: | 
          python -m waveform_fixed_rotation_cal
      - name: Running Inspiral Circuit 
        working-directory: ./Fixed_Roations_GSP
        run: | 
          python -m fixed_rotation_circ
      - name: Running Waveform Circuit 
        working-directory: ./Fixed_Roations_GSP
        run: | 
          python -m waveform_fixed_circ

      

