name: QuantumEncoding

on: 
  push:
    paths:
        - 'GroverRudolph_LPW/**'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Running Grover-Rudolph Algorithm
        run: | 
          python -m GroverRudolph
      - name: Running Linear-Piecewise Function
        run: | 
          python -m Linear_Piecewise
      - name: Testing
        run: |
          python -m TestGR
